
name-template: 'test-main-v$RESOLVED_VERSION'

tag-template: 'test-main-v$RESOLVED_VERSION'
tag-prefix: test-main-

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
    # What's Changed
    
    $CHANGES
    
    # Usage
    
    More info can be found in the [installation instructions](https://docs.epinio.io/installation/install_epinio).

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'kind/enhancement'
      - 'kind/dependencies'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'kind/bug'
      - 'kind/chore'
  default: patch

autolabeler:
  - label: 'test-main'
    files:
      - 'charts/test-main/Chart.yaml'
  - label: 'bug'
    files:
      - 'charts/test-main/Chart.yaml'
