apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  label:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  bucket: {{ .Release.Name | b64enc }}
