apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["aws", "s3", "rb", "s3://{{ .Release.Name }}", "--force"]
          volumeMounts:
            - name: aws-cli-config
              mountPath: /root/.aws
      restartPolicy: Never
      volumes:
        - name: aws-cli-config
          configMap:
            name: {{ .Release.Name }}

