name: Release Drafter

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    permissions:
      contents: write      
      pull-requests: write # write permission is required for autolabeler
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-releaser: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
